### ISSUE TITLE
Add serialization to the grid

### ISSUE THREAD

**Issue by wadlo** [BenjaTK/Criss-Cross#10]
An enhancement to make saving easier

- Serialize -> Returns Json string (https://docs.godotengine.org/en/stable/classes/class_json.html)
- Deserialize(string) -> Loads a grid's state from Json
- Load(string) -> loads a grid by ID
- Save(string) -> Saves a grid with the provided key

I think this would make sense in the core `grid2d.cs` file.

**Comment by BenjaTK** [comment]
I think maybe that should be handled by the user? Don't know if it's in the scope of the add-on.
